--- #YAML:1.0
name:               bootylicious
version:            0.900101
abstract:           Blog software
author:
    - Viacheslav Tykhanovskyi <vti@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:  {}
build_requires:  {}
requires:
    File::Basename:     0
    FindBin:            0
    Mojo:               0.99991
    perl:               5.008001
    Pod::Simple::HTML:  0
    Time::Local:        0
    Time::Piece:        0
resources:
    homepage:    http://getbootylicious.org
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/vti/bootylicious/tree/master
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
